feat(01-building-blocks): edited workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,23 +1,20 @@
 name: 01 - Building Blocks
-on:
-  push:
-  workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+on: push
+  
 jobs:
-  # This workflow contains a single job called "echo-hello"
   echo-hello:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    - name: Failed step
-      run: |
-        echo "I will fail"
+      - name: Say hello
+        run: echo "Hello, world!"
 
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-    - name: Say goodbye
-      run: echo "Goodbye!"
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say goodbye
+        run: echo "Goodbye"
